server.port = 8083
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:deliverydb

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=delivery-group
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.admin.fail-fast=false
spring.kafka.consumer.properties.spring.json.trusted.packages=com.sc.saga

spring.kafka.listener.retry-topic-suffix=-delivery-retry
spring.kafka.listener.dlt-topic-suffix=-delivery-dlt
spring.kafka.listener.retry.max-attempts=3
spring.kafka.listener.retry.initial-interval=1000
spring.kafka.listener.retry.multiplier=2.0

# Tracing Configuration
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4317}
